import Head from "next/head";
import Image from "next/image";
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import About from "@/components/About";
import Experience from "@/components/Experience";
import MySkills from "@/components/MySkills";
import Projects from "@/components/Projects";
import Contact from "@/components/Contact";
import Link from "next/link";
// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div
      className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden 
    scrollbar scrollbar-track-gray-400/30 scrollbar-thumb-green-300/40 z-0"
    >
      <Head>
        <title>Shahriar Ahmed Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* Header Start */}

      <Header />

      {/* Header Finished */}

      {/* Hero Start*/}

      <section id="hero" className="snap-start">
        <Hero />
      </section>

      {/* Hero Finished*/}

      {/* About Start*/}

      <section id="about" className="snap-center">
        <About />
      </section>

      {/* About Finished*/}

      {/* Experience Start */}

      <section id="experiences" className="snap-center">
        <Experience />
      </section>

      {/* Experience Finished */}

      {/* Skills Start */}

      <section id="skills" className="snap-start">
        <MySkills />
      </section>

      {/* Skills Finished */}

      {/* Projects Start*/}

      <section id="projects" className="snap-start">
        <Projects />
      </section>

      {/* Projects Finished*/}

      {/* Contact Me */}

      <section id="contact" className="snap-center">
        <Contact />
      </section>

      {/* Contact Me Finished */}

      <Link href="#hero">
        <footer className="sticky bottom-4 w-full cursor-pointer">
          <div className="flex items-center justify-center">
            <Image
              width={100}
              height={100}
              className="h-7 w-7 rounded-full filter grayscale hover:grayscale-0 cursor-pointer"
              src="/mine.jpg"
              alt="SHAHRIAR AHMED"
            />
          </div>
        </footer>
      </Link>
    </div>
  );
}
